### ISSUE TITLE
throw error `Server section is required in config.` on Windows

### ISSUE THREAD

**Issue by DuanPengfei** [akyuujs/akyuu#16]
```
C:\Users\fei\Desktop\share\webui\node_modules\.npminstall\akyuu\0.2.0\akyuu\index.js:11
    throw new Error("Server section is required in config.");
    ^

Error: Server section is required in config.
    at Object.<anonymous> (C:\Users\fei\Desktop\share\webui\node_modules\.npminstall\akyuu\0.2.0\akyuu\index.js:11:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\fei\Desktop\share\webui\app.js:1:77)
    at Module._compile (module.js:569:30)
```

**Comment by clChenLiang** [comment]
Mark 一下，应该是在 

> akyuu/config 中
```
const configDir = process.env.NODE_CONFIG_DIR || path.join(require.main.filename, "..", "/config");
```
出的问题。
没有配置 `NODE_CONFIG_DIR` 所致

**Comment by DuanPengfei** [comment]
👌
